# Generated by Django 4.1.7 on 2023-03-08 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0008_alter_job_slug_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='onwer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apply',
            name='cover_letter',
            field=models.TextField(max_length=500),
        ),
    ]
